### ISSUE TITLE
Failed to build index - Toolbox Version 0.0.41

### ISSUE THREAD

**Issue by stefanpoensgen** [shopwareLabs/shopware6-phpstorm-plugin#186]
```
com.intellij.diagnostic.PluginException: Failed to build index 'de.shyim.shopware6.backend.system-config' for file file:///home/stefan/code/shop/src/MyBundle/Resources/config/config.xml (id = 3303) (file type = XML) [Plugin: de.shyim.shopware6]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	...

```

**Comment by shyim** [comment]
is fixed with https://github.com/shopwareLabs/shopware6-phpstorm-plugin/commit/13db65384646a9714a6ba3b05f3a0e4d7ec00b53
